name: Patrick-Owusu Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Print greeting
        run: echo "Hello from Patrick!"

      - name: Run Python version
        run: python --version
Add Patrick workflow with greeting and python version
